### ISSUE TITLE
R-T3.4-14: The IaC miner must have a gui to export the crawled projects

### ISSUE THREAD

**Issue by dardin88** [radon-h2020/radon-defect-prediction-api#12]
ID | R-T3.4-14
-- | --
Section | WP3: Methodology and Quality Assurance Requirements
Type | FUNCTIONAL_SUITABILITY
User Story | As an Operations Engineer/QoS Engineer/Release Manager, I want to export the data concerning the projects that I crawled using the IaC miner
Requirement | The IaC miner must allow developers to dump the crawled repository in a suitable structured format (e.g., CSV, SQL)
Priority | Must have
Affected Tools | DEFECT_PRED_TOOL
Means of Verification | Direct implementation on IDE, feature checklist, case-study
Dependency | R-T3.4-12

**Comment by stefanodallapalma** [comment]
![export-collected-projects](https://user-images.githubusercontent.com/18099827/98453010-df2a6880-2154-11eb-9e68-9006beffb23b.gif)

Closing @gcasale
