### ISSUE TITLE
R-T3.4-17: The Defect Prediction Framework should allow developers to manually modify the fixing commits

### ISSUE THREAD

**Issue by dardin88** [radon-h2020/radon-defect-prediction-api#13]
ID | R-T3.4-17
-- | --
Section | WP3: Methodology and Quality Assurance Requirements
Type | FUNCTIONAL_SUITABILITY
User Story | Some fixing commits automatically crawled could be false positive. Therefore, the IaC miner should allow the Operations Engineer/QoS Engineer/Release Manager to manually modify them
Requirement | The Defect Prediction Framework should allow developers to manually modify the fixing commits
Priority | Should have
Affected Tools | DEFECT_PRED_TOOL
Means of Verification | Direct implementation on IDE, feature checklist, case-study

**Comment by gcasale** [comment]
Approved

**Comment by stefanodallapalma** [comment]
![fixing-commits](https://user-images.githubusercontent.com/18099827/98452997-bc984f80-2154-11eb-83e0-ffd27730a322.gif)

Closing. @gcasale
