### ISSUE TITLE
R-T3.4-1: The defect-prediction tool must provide APIs to be easily integrated with other tools in RADON and with the IDE	  

### ISSUE THREAD

**Issue by dardin88** [radon-h2020/radon-defect-prediction-api#2]
ID | R-T3.4-1
-- | --
Section | WP3: Methodology and Quality Assurance Requirements
Type | FUNCTIONAL_SUITABILITY
User Story | As an Operations Engineer I want the tool to be integrated with the IDE and other tools in RADON
Requirement | The defect-prediction tool must provide APIs to be easily integrated with other tools in RADON and with the IDE
Extended Description | The tool must be integrated with other tools in RADON as well as a plugin in popular IDEs such as Eclipse (e.g., Eclipse Che). Mainly, the requirement will be fulfilled to make sure the defect-prediction tool to be integrated with Winery/IDE as well as the delivery toolchain
Priority | Must have
Affected Tools | DEFECT_PRED_TOOL
Means of Verification | Direct implementation on IDE, feature checklist, case-study
Dependency |

**Comment by stefanodallapalma** [comment]
@gcasale 
This requirement is satisfied, though further APIs will be provided in the next future versions of the tool.

**Comment by gcasale** [comment]
Closed
