### ISSUE TITLE
R-T3.4-5: The defect-prediction tool could provide a defect threat level to architecture elements and predict threat-level defects under certain infrastructure assumptions.

### ISSUE THREAD

**Issue by dardin88** [radon-h2020/radon-defect-prediction-api#4]
ID | R-T3.4-5
-- | --
Section | WP3: Methodology and Quality Assurance Requirements
Type | FUNCTIONAL_SUITABILITY
User Story | As an Operations Engineer/QoS Engineer/Release Manager I want the tool to show me a score of the correctness of my infrastructure's elements (e.g., a score of the defect threat-level)
Requirement | The defect-prediction tool must provide a defect threat level to architecture elements and predict threat-level defects under certain infrastructure assumptions.
Extended Description | The user must have the opportunity to prioritize the actions to solve defects.
Priority | Must have
Affected Tools | DEFECT_PRED_TOOL
Means of Verification | Direct implementation on IDE, feature checklist, case-study
Dependency | R-T3.4-1 https://github.com/radon-h2020/radon-defect-prediction-api/issues/2 (could use) <br> R-T3.4-2 https://github.com/radon-h2020/radon-defect-prediction-api/issues/4 (could use) <br> R-T3.4-3 https://github.com/radon-h2020/radon-defect-prediction-api/issues/3 (could use)

**Comment by stefanodallapalma** [comment]
@gcasale 
Status: TODO

**Comment by stefanodallapalma** [comment]
Replace by #9

**Comment by gcasale** [comment]
Approved
