### ISSUE TITLE
R-T3.4-10: The defect-prediction tool must improve performances over manual inspection

### ISSUE THREAD

**Issue by dardin88** [radon-h2020/radon-defect-prediction-api#5]
ID | R-T3.4-10
-- | --
Section | WP3: Methodology and Quality Assurance Requirements
Type | PERFORMANCE_EFFICIENCY
User Story | As an Operations Engineer I want the tool to find more defects than manual inspection
Requirement | The defect-prediction tool must improve performances over manual inspection
Extended Description | The tool needs to finish its analysis in less time with respect to manual inspection, without loss of effectiveness
Priority | Must have
Affected Tools | DEFECT_PRED_TOOL
Means of Verification | User study with performance improved by at least 15%
Dependency |

**Comment by stefanodallapalma** [comment]
@gcasale 
This requirement will take time to be addressed. We are designing industrial cases studies with ENG and PRQ to address it.

**Comment by stefanodallapalma** [comment]
Hi everyone @gcasale @dardin88 

Considering that the goal of the tool is to prioritize manual inspection to improve the overall code quality, I suggest to upgrade this requirement (therefore update title and description) so to provide an industrial survey with RADON industrial partners to understand whether they perceive the defect prediction tool helpful in their daily tasks.
The reason for this is that, unfortunately, the evaluation of this requirement is impractical, as it would require a controlled experiment or an ethnography. Such study should involve multiple developers or operators detecting manually injected faults using or not the defect prediction tool. At this stage and under the COVID pandemic, such a controlled experiment cannot be performed.

**Comment by gcasale** [comment]
Agreed, if the industrial partners also agree to it

**Comment by stefanodallapalma** [comment]
We have already prepared and shared a survey that the partners (ENG and PRQ) agreed to fill in the next few months.
